baseURL: "https://piyushpahujadaisspanishblog.onrender.com"
languageCode: "en-us"
title: "Piyush Pahuja - A DAIS Spanish Language Blog"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
